object Versions {
    const val coreKtx = "1.7.0"
    const val lifecycle = "2.6.2"
    const val activityCompose = "1.8.1"
    const val composeBom = "2023.03.00"
    const val composeMaterial3 = "1.2.0-alpha09"
    const val navigationRuntimeKtx = "2.7.3"
    const val junit = "4.13.2"
    const val androidxJunit = "1.1.5"
    const val espresso = "3.5.1"
    const val navigationCompose = "2.6.0"
    const val dagger = "2.44"
    const val hiltViewModel = "1.0.0-alpha02"
    const val constraintlayout = "2.1.4"
    const val retrofit = "2.9.0"
    const val coroutinesCore = "1.7.2"
    const val lifecycleViewmodel = "2.6.1"
    const val loggingInterceptor = "4.11.0"
    const val splashscreen = "1.0.0"
}